version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - ./pg_seed/:/docker-entrypoint-initdb.d/ # Init path
      - ./dist/postgres_data:/var/lib/postgresql/data/ # Persisent Data
      # - ./node-solution/errors/log.csv:/usr/log.csv # Import errors from the host into the docker